"""Add Recipe and Machine

Revision ID: 6f64b149300c
Revises: a7521358dcf1
Create Date: 2026-05-15 00:05:46.961518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f64b149300c'
down_revision = 'a7521358dcf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('result_item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_item_id', sa.Integer(), nullable=False),
    sa.Column('req_amount', sa.Integer(), nullable=False),
    sa.Column('craft_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_item_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['result_item_id'], ['crop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine')
    op.drop_table('recipe')
    # ### end Alembic commands ###
