"""Add xp and unlock_level

Revision ID: 7b1a13dce884
Revises: 6f64b149300c
Create Date: 2026-05-15 00:16:40.952870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1a13dce884'
down_revision = '6f64b149300c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlock_level', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlock_level', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('xp')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('unlock_level')

    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.drop_column('unlock_level')

    # ### end Alembic commands ###
