"""Add width and height to Plot

Revision ID: 8a16077db2cf
Revises: e4a4b6b58ce0
Create Date: 2026-05-15 19:05:14.510882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a16077db2cf'
down_revision = 'e4a4b6b58ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
