"""Rename FarmPlot to Plot and add state

Revision ID: a7521358dcf1
Revises: 3ac5244e13ed
Create Date: 2026-05-14 23:13:50.327706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7521358dcf1'
down_revision = '3ac5244e13ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('planted_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('farm_plot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_plot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('crop_id', sa.INTEGER(), nullable=True),
    sa.Column('planted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_empty', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('plot')
    # ### end Alembic commands ###
