"""Add machine_type

Revision ID: cd23c107f968
Revises: 7b1a13dce884
Create Date: 2026-05-15 00:31:21.602751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd23c107f968'
down_revision = '7b1a13dce884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_type', sa.String(length=50), server_default='basic', nullable=False))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_machine_type', sa.String(length=50), server_default='basic', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('required_machine_type')

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('machine_type')

    # ### end Alembic commands ###
