"""Add plot grid fields

Revision ID: e4a4b6b58ce0
Revises: cd23c107f968
Create Date: 2026-05-15 00:41:15.501567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a4b6b58ce0'
down_revision = 'cd23c107f968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_coord', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('y_coord', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_owned', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_column('is_owned')
        batch_op.drop_column('y_coord')
        batch_op.drop_column('x_coord')

    # ### end Alembic commands ###
